### ISSUE TITLE
[Errno 5] Input/output error 

### ISSUE THREAD

**Issue by avtehnik** [mushketer888/pyrtd2660i2c#1]
Hi, yesterday i was try to use your code on raspberry pi, and i got this error, 
after this display controller not showing anything on display, he still detected by i2c. 

pi@raspberrypi:~/pyrtd2660i2c $ sudo python main.py pcb8009/PCB800099-ttl800x480-24bit-at070tn90-2av1vga1hdmi-5key-IR2.bin
Opening bus...
Enter ISP?
Send SPI command
[70]
15675411
JEDEC ID: 0xEF3013

flash matches!
Manufacturer
Winbond

Chip: W25X40

Size: 512KB

[66]
Flash status register: 0x00

Flashing "/home/pi/pyrtd2660i2c/pcb8009/PCB800099-ttl800x480-24bit-at070tn90-2av1vga1hdmi-5key-IR2.bin" to controller
Erasing...
[136]
[105]
[161]
Traceback (most recent call last):
  File "main.py", line 408, in <module>
    ProgramFlash(filenam,256\* 1024) # zapisj
  File "main.py", line 237, in ProgramFlash
    SPICommonCommand(E_CC_ERASE, 0xc7, 0, 0, 0); #// Chip Erase
  File "main.py", line 89, in SPICommonCommand
    b = bus.read_i2c_block_data(0x4a,0x60,1)
IOError: [Errno 5] Input/output error

**Comment by avtehnik** [comment]
The problem was in wiring, i take other cable (about 1m long) and everything went  good

**Comment by raparram** [comment]
Hi! you did it from the raspberry? any advice?

**Comment by pragyan010** [comment]
Can I connect 12c pins (sda,sal,gnd) to raspberry pi 3 pins and flash firmware ?
